# Generated by Django 5.1.2 on 2024-11-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
